#!/usr/bin/perl -wnp

BEGIN {
    sub qepics {
        my $var = shift;

        if (exists $ENV{$var}) { # allow any to be overridden from environment
            return $ENV{$var};

        } elsif ($var =~ m/EPICS_([A-Z]+)_ARCH/) {
            my $ret = `dh_epics_hostarch $1`;
            chomp($ret);
            return $ret;

        } elsif ($var eq "EPICS_BASE") {
            return "usr/lib/epics";
        }
    }
}

s/(\$\{(EPICS_[A-Z_]+)\})/qepics($2) || $1/eg;
